### ISSUE TITLE
Reason for some typedefs in SOILWAT2 code?

### ISSUE THREAD

**Issue by nip5** [DrylandEcology/SOILWAT2#193]
@dschlaep 
I've been wondering about the reason behind the simple `typedefs` such as: `RealD`, `RealF`, `IRealD`, etc. There is a comment in the code that says it is in order to make them more malleable but I was hoping you could expand on that. Do I need to use these in the unit tests or could I, for example, use `double` instead of `RealD`?

**Comment by dschlaep** [comment]
These have been in the code since ancient time -- well before my time. There is some intent that the functions in module `SW_Flow_lib` can live independently from `SOILWAT`, i.e., they are not using those typedefs. Otherwise, the remaining code attempts to use these typedefs -- more or less consistently.

**Comment by nip5** [comment]
So we would prefer to use built in types rather than the `typedefs` defined, to keep it so modules can run independently of `SOILWAT`, correct? Or is that only the case in `SW_Flow_lib`?

**Comment by nip5** [comment]
For example, that file uses `double` while SW_SoilWater primarily uses `RealD`.

**Comment by dschlaep** [comment]
I gather that the ancient intent was that only th functions in `SW_Flow_lib` might be useful outside of a `SOILWAT` context -- everything else is `SOILWAT` and strives to use its typedefs.
