### ISSUE TITLE
Running Sum of Squares function incorrect.

### ISSUE THREAD

**Issue by chaukap** [DrylandEcology/SOILWAT2#232]
In https://github.com/DrylandEcology/STEPWAT2/issues/63 we noticed that standard deviation values were slightly off when using the final_running_sd() function in generic.c. The error comes from the get_running_sqr function which is called right before final_running_sd. 

In the documentation it lists this website:
https://www.johndcook.com/blog/standard_deviation/

But it looks like whoever put this into SOILWAT forgot to add one thing. The website calculates the sum of squares as:
old_sqr + (val_to_add - mean_prev) * (val_to_add - mean_current)

where our code only has:
(val_to_add - mean_prev) * (val_to_add - mean_current)

This has been throwing off our values because get_running_sqr is only returning the current value's sum of squares, not the entire set's.

I would like to open a new branch to correct this issue. I will call the branch bugfix_[issueNumber]_chaukap unless you ave any objections @dschlaep?

**Comment by dschlaep** [comment]
The following statement is incorrect:
```
where our code only has:
(val_to_add - mean_prev) * (val_to_add - mean_current)
```

Read the documentation of `get_running_sqr` carefully, particularly what the function returns, i.e, the "summand" and not the "sum". That means that the sum over the squares must be accumulated by the caller to `get_running_sqr`. You can find correct use cases in the function `do_running_agg()` in file `SW_Output_array.c` and in the unit tests for `RunningSD`. They all appear to work correctly.

You haven't convinced me that there is anything wrong on the `SOILWAT2` side. Create a new unit test that fails because of the situation that you describe.

**Comment by chaukap** [comment]
Sorry about the confusion. I fixed my implementation and will close this branch.
