### ISSUE TITLE
Has file `SW_Main_Function.c` become obselete with file `SW_Main_lib.c`?

### ISSUE THREAD

**Issue by dschlaep** [DrylandEcology/SOILWAT2#90]
A recent pr https://github.com/Burke-Lauenroth-Lab/SOILWAT2/commit/2a9f262cca4aecbd418b05300d73174cfa5bf282 introduced a new file `SW_Main_lib.c` which removed all functionality from `SW_Main.c` except the `main()` function for `SOILWAT2` standalone.

It seems that file `SW_Main_Function.c` which has only been used by `STEPWAT2` may no longer be needed/has become redundant. However, this is not quiet obvious to me because this file defines a new function `main_function` which is not otherwise present yet almost identical to `main`. `STEPWAT2` uses this function in its function `ST_main.c/print_soilwat_output()` under conditions of `isPartialSoilwatOutput` -- I am not familiar enough with `STEPWAT2` to know whether and how `main_function` is in use.

Can we delete `SW_Main_Function.c` in favor of `SW_Main_lib.c`? Or can we merge these two files and keep the function `main_function` and make it generally usable?

**Comment by kpalmqui** [comment]
This was implemented by Ashish and the explanation is documented at the top of the SW_Main.c (see below). This was the first attempt at saving all of the SOILWAT2 output within STEPWAT2 but was not done correctly. I think we should be able to remove the SW_Main_Function.c - Brenden, you have been working on this code most recently and you look and confirm?

Comment from SW_Main_Function.c
  Added this file ‘SW_Main_Function.c’ that is similar to  as SW_Main.c except SW_Main_Function.c does not have main() function.
  Added this because of one requirement: to have Soilwat all the output in the Stepwat, while running  Stepwat  with soilwat.
  Like  running Soilwat standalone output , we wanted  this,  all the output files in stepwat as well.

  So one of the solution was to  include soilwat  SW_Main.c file for compile in Stepwat project  and from Stepwat main() function flow,
  we can call the main() function of Soilwat's  SW_Main.c .

  However, we can not include  SW_Main.c file for compile in Stepwat project,  as  any c/cpp project can have only one entry/start point
  as main() function so  any project can not have more than one main() functions.
  But somehow for this requirement need to run two main() function flow (one Soilwat standalone flow, second normal stepwat flow).
  So I had to create duplicate file  SW_Main_Function.c  from SW_Main.c , here main() function renamed so it will not give conflict
  with Stepwat main() function and did some minor cosmetic changes for not closing log file pointers, that was  shared with both
  stepwat and soilwat.
